name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew clean :app:assembledebug
      - name:  Automated Version Bump
        uses:  phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit-message: 'CI: bumps version to {{version}} [skip ci]'
      - name: Create release and upload apk
        uses: underwindfall/create-release-with-debugapk@v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{version}}
          asset_path: app/build/outputs/apk/debug/app-debug.apk
          asset_name: GithubActionDemo.apk
          asset_content_type: application/zip
